### ISSUE TITLE
缺SVD file

### ISSUE THREAD

**Issue by genokolar** [RT-Thread-Studio/sdk-debugger-pyocd#2]
```
pyocd flash -t nrf52 -e sector -f 2M _build/nrf52_kbd.hex
0000544:WARNING:loader:unable to open builtin SVD file: [Errno 2] No such file or directory: 'C:\\Users\\Geno\\AppData\\Local\\Temp\\_MEI54042\\pyocd\\debug\\svd\\svd_data.zip'
Traceback (most recent call last):
  File "pyocd\debug\svd\loader.py", line 34, in from_builtin
  File "pkg_resources\__init__.py", line 1151, in resource_stream
  File "pkg_resources\__init__.py", line 1399, in get_resource_stream
  File "pkg_resources\__init__.py", line 1402, in get_resource_string
  File "pkg_resources\__init__.py", line 1571, in _get
  File "c:\users\yaxing.chen\documents\pyocd\venv3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 341, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Geno\\AppData\\Local\\Temp\\_MEI54042\\pyocd\\debug\\svd\\svd_data.zip'
[---|---|---|---|---|---|---|---|---|----]
[========================================]
```

如上，打包里面缺SVD file

**Comment by Guozhanxin** [comment]
嗯，打包的问题

**Comment by Guozhanxin** [comment]
已修复
